import { Activity, Club, RegistrationMode, ActivityStatus, Level, User, Post, PostType, Notification, NotificationType } from './types';

export const TAIWAN_PATH_DATA = [
  { id: '台北市', d: 'M 162 15 L 175 15 L 178 25 L 170 32 L 160 25 Z' },
  { id: '新北市', d: 'M 155 10 L 185 10 L 195 35 L 185 55 L 155 50 L 145 30 Z' },
  { id: '基隆市', d: 'M 180 8 L 190 8 L 192 15 L 182 18 Z' },
  { id: '桃園市', d: 'M 135 25 L 155 25 L 158 45 L 130 55 L 120 40 Z' },
  { id: '新竹縣', d: 'M 125 50 L 145 50 L 155 75 L 130 85 L 115 70 Z' },
  { id: '新竹市', d: 'M 118 58 L 128 58 L 130 65 L 120 68 Z' },
  { id: '苗栗縣', d: 'M 105 75 L 130 80 L 140 110 L 110 115 L 95 95 Z' },
  { id: '台中市', d: 'M 90 110 L 135 105 L 165 135 L 130 155 L 85 145 Z' },
  { id: '彰化縣', d: 'M 75 145 L 95 145 L 100 175 L 70 175 Z' },
  { id: '南投縣', d: 'M 105 145 L 150 145 L 170 200 L 135 225 L 105 200 Z' },
  { id: '雲林縣', d: 'M 60 175 L 95 175 L 100 205 L 55 205 Z' },
  { id: '嘉義縣', d: 'M 50 205 L 120 210 L 130 245 L 60 255 L 45 235 Z' },
  { id: '嘉義市', d: 'M 75 220 L 85 220 L 87 230 L 77 233 Z' },
  { id: '台南市', d: 'M 40 245 L 110 245 L 115 295 L 45 305 L 30 275 Z' },
  { id: '高雄市', d: 'M 45 305 L 105 295 L 145 345 L 120 395 L 80 410 L 55 385 Z' },
  { id: '屏東縣', d: 'M 90 405 L 130 395 L 145 445 L 125 505 L 100 505 L 85 465 Z' },
  { id: '宜蘭縣', d: 'M 175 45 L 205 50 L 215 100 L 185 120 L 165 85 Z' },
  { id: '花蓮縣', d: 'M 165 120 L 205 120 L 210 280 L 160 280 L 145 200 Z' },
  { id: '台東縣', d: 'M 150 285 L 195 285 L 190 425 L 140 435 L 130 350 Z' },
  { id: '澎湖縣', d: 'M 10 180 L 30 180 L 35 210 L 15 215 Z' },
  { id: '金門縣', d: 'M 5 50 L 25 50 L 25 70 L 5 70 Z' },
  { id: '連江縣', d: 'M 5 10 L 20 10 L 20 20 L 5 20 Z' },
];

export const MOCK_USER: User = {
  id: 'u1',
  name: 'Alex Chen',
  avatar: 'https://picsum.photos/id/64/200/200',
  isClubAdmin: true,
  registeredActivityIds: ['a1', 'a8'],
  joinedClubIds: ['c1', 'c2'],
  managedClubIds: ['c1'],
};

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'n1',
    type: NotificationType.ACTIVITY,
    title: '活動行前提醒',
    content: '您報名的「週二晚間歡樂羽球」將於明日 19:00 開始，請準時出席。',
    time: '1小時前',
    isRead: false,
    linkId: 'a1'
  },
  {
    id: 'n2',
    type: NotificationType.INTERACTION,
    title: '新的留言',
    content: 'Sarah Wu 回覆了您的貼文：「這張照片拍得真好！」',
    time: '3小時前',
    isRead: false,
    linkId: 'p3'
  },
  {
    id: 'n3',
    type: NotificationType.SYSTEM,
    title: '系統公告',
    content: 'GoGo Sports 平台將於本週日凌晨 02:00 進行系統維護，預計暫停服務 2 小時。',
    time: '1天前',
    isRead: true,
  },
  {
    id: 'n4',
    type: NotificationType.INVITE,
    title: '社團邀請',
    content: '「台北夜跑團」邀請您加入社團。',
    time: '2天前',
    isRead: true,
    linkId: 'c5'
  },
  {
    id: 'n5',
    type: NotificationType.ACTIVITY,
    title: '候補成功通知',
    content: '恭喜！您已成功候補上「陽明山東西大縱走」，請盡快確認報名資訊。',
    time: '3天前',
    isRead: true,
    linkId: 'a4'
  }
];

export const MOCK_CLUBS: Club[] = [
  {
    id: 'c1',
    name: '台北羽球狂熱團',
    logo: 'https://picsum.photos/id/10/200/200',
    rating: 4.8,
    membersCount: 1205,
    description: '每週二四固定開團，歡迎新手老手一起流汗！',
    tags: ['羽球', '室內', '競技'],
  },
  {
    id: 'c2',
    name: '山野行者 Hiking Club',
    logo: 'https://picsum.photos/id/12/200/200',
    rating: 4.9,
    membersCount: 3400,
    description: '探索台灣百岳與古道，安全第一，樂趣第二。',
    tags: ['登山', '戶外', '風景'],
  },
  {
    id: 'c3',
    name: '海人水上俱樂部',
    logo: 'https://picsum.photos/id/433/200/200',
    rating: 4.7,
    membersCount: 850,
    description: '專注於 SUP、衝浪與自由潛水，享受海洋的擁抱。',
    tags: ['SUP', '水上', '夏天'],
  },
  {
    id: 'c4',
    name: '鐵拳格鬥學院',
    logo: 'https://picsum.photos/id/158/200/200',
    rating: 5.0,
    membersCount: 420,
    description: '拳擊、泰拳教學與實戰切磋，釋放壓力的好去處。',
    tags: ['拳擊', '格鬥', '健身'],
  },
  {
    id: 'c5',
    name: '台中夜光跑步會',
    logo: 'https://picsum.photos/id/160/200/200',
    rating: 4.6,
    membersCount: 2100,
    description: '晚上跑更舒服，發現台中夜晚的美好。',
    tags: ['夜跑', '台中', '社群'],
  },
  {
    id: 'c6',
    name: '南台灣排球之友',
    logo: 'https://picsum.photos/id/170/200/200',
    rating: 4.5,
    membersCount: 680,
    description: '高雄、屏東地區排球愛好者聚集地。',
    tags: ['排球', '南台灣', '運動'],
  },
  {
    id: 'c7',
    name: '府城跑者',
    logo: 'https://picsum.photos/id/180/200/200',
    rating: 4.9,
    membersCount: 1550,
    description: '台南在地跑團，跑步是為了吃更多台南美食！',
    tags: ['路跑', '台南', '美食'],
  },
  {
    id: 'c8',
    name: '風城單車社',
    logo: 'https://picsum.photos/id/190/200/200',
    rating: 4.7,
    membersCount: 420,
    description: '新竹地區單車愛好者，分享路線與裝備。',
    tags: ['單車', '新竹', '戶外'],
  },
  {
    id: 'c9',
    name: '桃園越野魂',
    logo: 'https://picsum.photos/id/200/200/200',
    rating: 4.8,
    membersCount: 300,
    description: '桃園近郊步道開發者，體驗腳下的每一寸土地。',
    tags: ['越野跑', '桃園', '極限'],
  },
  {
    id: 'c10',
    name: '中台灣攀岩聯盟',
    logo: 'https://picsum.photos/id/210/200/200',
    rating: 4.9,
    membersCount: 520,
    description: '台中最活躍的攀岩社群，新手友善。',
    tags: ['攀岩', '台中', '運動'],
  },
  {
    id: 'c11',
    name: '花東極限運動聯盟',
    logo: 'https://picsum.photos/id/220/200/200',
    rating: 4.8,
    membersCount: 250,
    description: '專注於花蓮、台東的冒險活動。',
    tags: ['獨木舟', '冒險', '花東'],
  },
  {
    id: 'c12',
    name: '台北划水部隊',
    logo: 'https://picsum.photos/id/230/200/200',
    rating: 4.4,
    membersCount: 180,
    description: '大佳河濱滑水愛好者，夏天必去！',
    tags: ['滑水', '台北', '水上'],
  },
  {
    id: 'c13',
    name: '台中重訓大師',
    logo: 'https://picsum.photos/id/240/200/200',
    rating: 4.7,
    membersCount: 890,
    description: '科學化訓練，專業健身知識分享。',
    tags: ['重訓', '健身', '科學'],
  },
  {
    id: 'c14',
    name: '港都韻律瑜珈',
    logo: 'https://picsum.photos/id/250/200/200',
    rating: 4.6,
    membersCount: 1200,
    description: '高雄地區瑜珈與皮拉提斯課程推廣。',
    tags: ['瑜珈', '健身', '高雄'],
  },
  {
    id: 'c15',
    name: '冬山河划友會',
    logo: 'https://picsum.photos/id/260/200/200',
    rating: 4.5,
    membersCount: 340,
    description: '宜蘭划船與獨木舟推廣。',
    tags: ['划船', '宜蘭', '風景'],
  },
  {
    id: 'c16',
    name: '北台灣潛水俱樂部',
    logo: 'https://picsum.photos/id/270/200/200',
    rating: 4.9,
    membersCount: 650,
    description: '基隆、東北角潛水，守護海洋之美。',
    tags: ['潛水', '海洋', '北台灣'],
  }
];

export const MOCK_ACTIVITIES: Activity[] = [
  {
    id: 'a1',
    clubId: 'c1',
    hostId: 'u1',
    approvalMode: 'AUTO' as const,
    title: '週二晚間歡樂羽球 (含教練指導)',
    date: '2023-11-14',
    time: '19:00 - 21:00',
    location: '台北市大同運動中心',
    price: 250,
    mode: RegistrationMode.LIMITED,
    status: ActivityStatus.OPEN,
    maxParticipants: 16,
    currentInternalCount: 4,
    currentAppCount: 8,
    level: Level.INTERMEDIATE,
    image: 'https://picsum.photos/id/192/600/400',
    description: '本週二固定團練，會有專業教練陪打指導一小時。使用 RSL 3 號球。',
    tags: ['羽球', '教練', '冷氣'],
    lat: 25.0634, lng: 121.5196,
  },
  {
    id: 'a2',
    clubId: 'c2',
    hostId: 'u1',
    approvalMode: 'AUTO' as const,
    title: '合歡北峰+西峰單攻 (百岳挑戰)',
    date: '2023-11-18',
    time: '04:00 集合',
    location: '南投縣仁愛鄉',
    price: 1200,
    mode: RegistrationMode.OPEN,
    status: ActivityStatus.OPEN,
    currentAppCount: 42,
    groups: ['攻頂挑戰組', '北峰休閒組', '攝影耍廢組'],
    level: Level.ADVANCED,
    image: 'https://picsum.photos/id/1018/600/400',
    description: '挑戰七上八下的西峰，需具備一定體能。費用包含保險與嚮導費，交通自理或申請共乘。',
    tags: ['百岳', '登山', '高強度'],
    lat: 23.9747, lng: 121.2053,
  },
  {
    id: 'a3',
    clubId: 'c1',
    hostId: 'u1',
    approvalMode: 'AUTO' as const,
    title: '週四新手友善羽球局',
    date: '2023-11-16',
    time: '20:00 - 22:00',
    location: '台北市信義區信義國中體育館',
    price: 200,
    mode: RegistrationMode.LIMITED,
    status: ActivityStatus.FULL,
    maxParticipants: 12,
    currentInternalCount: 6,
    currentAppCount: 6,
    level: Level.BEGINNER,
    image: 'https://picsum.photos/id/158/600/400',
    description: '專為新手開設，亦歡迎中手陪打。',
    tags: ['羽球', '新手', '交友'],
    lat: 25.0336, lng: 121.5636,
  },
  {
    id: 'a4',
    clubId: 'c2',
    hostId: 'u1',
    approvalMode: 'AUTO' as const,
    title: '陽明山東西大縱走 (十連峰)',
    date: '2023-11-25',
    time: '06:00 集合',
    location: '台北市士林區風櫃嘴登山口',
    price: 300,
    mode: RegistrationMode.OPEN,
    status: ActivityStatus.OPEN,
    currentAppCount: 85,
    groups: ['全程組(10峰)', '半程組(5峰)'],
    level: Level.INTERMEDIATE,
    image: 'https://picsum.photos/id/1036/600/400',
    description: '台北郊山之王，練腳力的好地方。',
    tags: ['縱走', '健行', '風景'],
    lat: 25.1086, lng: 121.5619,
  },
  {
    id: 'a5',
    clubId: 'c1',
    hostId: 'u1',
    approvalMode: 'AUTO' as const,
    title: '週末 3v3 籃球鬥牛賽',
    date: '2023-11-19',
    time: '14:00',
    location: '台北市新生高架橋下籃球場',
    price: 100,
    mode: RegistrationMode.LIMITED,
    status: ActivityStatus.OPEN,
    maxParticipants: 24,
    currentInternalCount: 0,
    currentAppCount: 12,
    level: Level.INTERMEDIATE,
    image: 'https://picsum.photos/id/829/600/400',
    description: '以球會友，自行組隊或現場分隊。',
    tags: ['籃球', '室外', '熱血'],
    lat: 25.0432, lng: 121.5320,
  },
  {
    id: 'a6',
    clubId: 'c3',
    hostId: 'u1',
    approvalMode: 'AUTO' as const,
    title: '龍洞 SUP 日出團',
    date: '2023-11-26',
    time: '04:30 集合',
    location: '新北市貢寮區龍洞',
    price: 1500,
    mode: RegistrationMode.OPEN,
    status: ActivityStatus.OPEN,
    currentAppCount: 18,
    groups: ['日出團', '上午團'],
    level: Level.BEGINNER,
    image: 'https://picsum.photos/id/445/600/400',
    description: '在平靜的海面上欣賞絕美日出，教練隨行拍攝美照。',
    tags: ['SUP', '水上活動', '風景'],
    lat: 25.0031, lng: 121.9249,
  },
  {
    id: 'a7',
    clubId: 'c4',
    hostId: 'u1',
    approvalMode: 'AUTO' as const,
    title: '週五格鬥體能特訓',
    date: '2023-11-17',
    time: '19:30 - 21:00',
    location: '台北市鐵拳格鬥學院 (信義館)',
    price: 400,
    mode: RegistrationMode.LIMITED,
    status: ActivityStatus.OPEN,
    maxParticipants: 12,
    currentInternalCount: 2,
    currentAppCount: 6,
    level: Level.ADVANCED,
    image: 'https://picsum.photos/id/342/600/400',
    description: '結合拳擊與高強度間歇運動，燃燒脂肪無極限。',
    tags: ['拳擊', '格鬥競技', '高強度'],
    lat: 25.0380, lng: 121.5700,
  },
  {
    id: 'a8',
    clubId: 'c1',
    hostId: 'u1',
    approvalMode: 'AUTO' as const,
    title: '晨間喚醒瑜珈',
    date: '2023-11-20',
    time: '07:00 - 08:00',
    location: '台北市大安森林公園',
    price: 150,
    mode: RegistrationMode.OPEN,
    status: ActivityStatus.OPEN,
    currentAppCount: 15,
    level: Level.BEGINNER,
    image: 'https://picsum.photos/id/338/600/400',
    description: '在草地上呼吸新鮮空氣，伸展肢體，迎接美好的一天。',
    tags: ['瑜珈', '身心靈', '戶外'],
    lat: 25.0295, lng: 121.5344,
  },
  {
    id: 'a9',
    clubId: 'c3',
    hostId: 'u1',
    approvalMode: 'AUTO' as const,
    title: '貢寮龍洞浮潛體驗',
    date: '2023-11-27',
    time: '10:00',
    location: '新北市貢寮區',
    price: 800,
    mode: RegistrationMode.LIMITED,
    status: ActivityStatus.OPEN,
    maxParticipants: 12,
    currentAppCount: 4,
    level: Level.BEGINNER,
    image: 'https://picsum.photos/id/123/600/400',
    description: '龍洞四季灣浮潛，含裝備與專業教練導引。',
    tags: ['浮潛', '水上活動', '生態'],
    lat: 25.0112, lng: 121.9167,
  },
  {
    id: 'a10',
    clubId: 'c5',
    hostId: 'u1',
    approvalMode: 'AUTO' as const,
    title: '台中望高寮夜跑團',
    date: '2023-11-15',
    time: '20:00',
    location: '台中市南屯區望高寮',
    price: 0,
    mode: RegistrationMode.OPEN,
    status: ActivityStatus.OPEN,
    currentAppCount: 25,
    level: Level.BEGINNER,
    image: 'https://picsum.photos/id/211/600/400',
    description: '一邊跑步一邊欣賞台中百萬夜景，跑完可以一起喝咖啡。',
    tags: ['夜跑', '風景', '健康'],
    lat: 24.1367, lng: 120.5983,
  },
  {
    id: 'a11',
    clubId: 'c6',
    hostId: 'u1',
    approvalMode: 'AUTO' as const,
    title: '高雄西子灣沙排友誼賽',
    date: '2023-11-21',
    time: '15:30',
    location: '高雄市鼓山區西子灣',
    price: 50,
    mode: RegistrationMode.LIMITED,
    status: ActivityStatus.OPEN,
    maxParticipants: 16,
    currentAppCount: 10,
    level: Level.INTERMEDIATE,
    image: 'https://picsum.photos/id/331/600/400',
    description: '南台灣暖暖的陽光，一起來打沙灘排球吧！',
    tags: ['排球', '沙灘', '熱血'],
    lat: 22.6256, lng: 120.2644,
  },
  {
    id: 'a12',
    clubId: 'c7',
    hostId: 'u1',
    approvalMode: 'AUTO' as const,
    title: '台南奇美博物館路跑',
    date: '2023-11-22',
    time: '06:30',
    location: '台南市仁德區奇美博物館',
    price: 0,
    mode: RegistrationMode.OPEN,
    status: ActivityStatus.OPEN,
    currentAppCount: 120,
    level: Level.BEGINNER,
    image: 'https://picsum.photos/id/456/600/400',
    description: '圍繞博物館園區晨跑，享受充滿藝術氣息的早晨。',
    tags: ['路跑', '台南', '風景'],
    lat: 22.9347, lng: 120.2261,
  },
  {
    id: 'a13',
    clubId: 'c8',
    hostId: 'u1',
    approvalMode: 'AUTO' as const,
    title: '新竹南寮單車半日遊',
    date: '2023-11-19',
    time: '14:00',
    location: '新竹市北區南寮漁港',
    price: 350,
    mode: RegistrationMode.OPEN,
    status: ActivityStatus.OPEN,
    currentAppCount: 15,
    level: Level.BEGINNER,
    image: 'https://picsum.photos/id/249/600/400',
    description: '騎乘十七公里海岸線，吹著海風，看著夕陽。',
    tags: ['單車', '休閒', '新竹'],
    lat: 24.8486, lng: 120.9161,
  },
  {
    id: 'a14',
    clubId: 'c9',
    hostId: 'u1',
    approvalMode: 'AUTO' as const,
    title: '桃園虎頭山越野跑',
    date: '2023-11-25',
    time: '08:00',
    location: '桃園市桃園區虎頭山',
    price: 200,
    mode: RegistrationMode.LIMITED,
    status: ActivityStatus.OPEN,
    maxParticipants: 20,
    currentAppCount: 8,
    level: Level.ADVANCED,
    image: 'https://picsum.photos/id/1043/600/400',
    description: '適合想要進階挑戰坡度的跑者，含補給。',
    tags: ['越野跑', '登山', '桃園'],
    lat: 24.9967, lng: 121.3283,
  },
  {
    id: 'a15',
    clubId: 'c10',
    hostId: 'u1',
    approvalMode: 'AUTO' as const,
    title: '台中室內抱石體驗',
    date: '2023-11-18',
    time: '19:00',
    location: '台中市西區攀岩館',
    price: 450,
    mode: RegistrationMode.LIMITED,
    status: ActivityStatus.OPEN,
    maxParticipants: 10,
    currentAppCount: 9,
    level: Level.BEGINNER,
    image: 'https://picsum.photos/id/1050/600/400',
    description: '新手友善，教練會指導基本發力與平衡技巧。',
    tags: ['攀岩', '室內', '挑戰'],
    lat: 24.1500, lng: 120.6600,
  },
  {
    id: 'a16',
    clubId: 'c11',
    hostId: 'u1',
    approvalMode: 'AUTO' as const,
    title: '花蓮七星潭獨木舟',
    date: '2023-12-01',
    time: '05:00',
    location: '花蓮縣新城鄉七星潭',
    price: 1600,
    mode: RegistrationMode.OPEN,
    status: ActivityStatus.OPEN,
    currentAppCount: 22,
    level: Level.INTERMEDIATE,
    image: 'https://picsum.photos/id/1053/600/400',
    description: '太平洋上的晨光，絕美海景獨木舟體驗。',
    tags: ['獨木舟', '花蓮', '風景'],
    lat: 24.0303, lng: 121.6295,
  },
  {
    id: 'a17',
    clubId: 'c1',
    hostId: 'u1',
    approvalMode: 'AUTO' as const,
    title: '松山羽球館團練',
    date: '2023-11-23',
    time: '18:00',
    location: '台北市松山區',
    price: 300,
    mode: RegistrationMode.LIMITED,
    status: ActivityStatus.OPEN,
    maxParticipants: 16,
    currentAppCount: 14,
    level: Level.INTERMEDIATE,
    image: 'https://picsum.photos/id/1054/600/400',
    description: '中級程度切磋，歡迎高手挑戰。',
    tags: ['羽球', '團練', '台北'],
    lat: 25.0500, lng: 121.5500,
  },
  {
    id: 'a18',
    clubId: 'c12',
    hostId: 'u1',
    approvalMode: 'AUTO' as const,
    title: '台北大佳河濱滑水體驗',
    date: '2023-11-20',
    time: '13:00',
    location: '台北市中山區大佳河濱公園',
    price: 1800,
    mode: RegistrationMode.LIMITED,
    status: ActivityStatus.OPEN,
    maxParticipants: 6,
    currentAppCount: 2,
    level: Level.BEGINNER,
    image: 'https://picsum.photos/id/1055/600/400',
    description: '都會區也能滑水！新手也能輕鬆上手。',
    tags: ['滑水', '水上', '台北'],
    lat: 25.0740, lng: 121.5430,
  },
  {
    id: 'a19',
    clubId: 'c13',
    hostId: 'u1',
    approvalMode: 'AUTO' as const,
    title: '台中南區重訓推廣課程',
    date: '2023-11-21',
    time: '19:00',
    location: '台中市南區健身工坊',
    price: 300,
    mode: RegistrationMode.LIMITED,
    status: ActivityStatus.OPEN,
    maxParticipants: 12,
    currentAppCount: 5,
    level: Level.BEGINNER,
    image: 'https://picsum.photos/id/1056/600/400',
    description: '學習深蹲與硬舉的基本姿勢，安全建立肌肉。',
    tags: ['重訓', '健身', '教學'],
    lat: 24.1200, lng: 120.6700,
  },
  {
    id: 'a20',
    clubId: 'c14',
    hostId: 'u1',
    approvalMode: 'AUTO' as const,
    title: '高雄美術館皮拉提斯',
    date: '2023-11-24',
    time: '10:00',
    location: '高雄市美術館大廳草皮',
    price: 400,
    mode: RegistrationMode.OPEN,
    status: ActivityStatus.OPEN,
    currentAppCount: 30,
    level: Level.BEGINNER,
    image: 'https://picsum.photos/id/1057/600/400',
    description: '核心訓練，改善體態，戶外舒適環境。',
    tags: ['皮拉提斯', '核心', '健身'],
    lat: 22.6560, lng: 120.2860,
  },
  {
    id: 'a21',
    clubId: 'c15',
    hostId: 'u1',
    approvalMode: 'AUTO' as const,
    title: '宜蘭冬山河划船趣',
    date: '2023-11-28',
    time: '14:30',
    location: '宜蘭縣冬山鄉冬山河親水公園',
    price: 500,
    mode: RegistrationMode.OPEN,
    status: ActivityStatus.OPEN,
    currentAppCount: 15,
    level: Level.BEGINNER,
    image: 'https://picsum.photos/id/1058/600/400',
    description: '漫遊冬山河，全家大小都適合。',
    tags: ['划船', '親子', '風景'],
    lat: 24.6800, lng: 121.8000,
  },
  {
    id: 'a22',
    clubId: 'c16',
    hostId: 'u1',
    approvalMode: 'AUTO' as const,
    title: '基隆潮境公園岸潛',
    date: '2023-11-26',
    time: '09:00',
    location: '基隆市潮境公園',
    price: 1200,
    mode: RegistrationMode.LIMITED,
    status: ActivityStatus.OPEN,
    maxParticipants: 8,
    currentAppCount: 6,
    level: Level.INTERMEDIATE,
    image: 'https://picsum.photos/id/1059/600/400',
    description: '北部最美潛點之一，魚群豐富。',
    tags: ['潛水', '基隆', '海洋'],
    lat: 25.1430, lng: 121.8030,
  },
  {
    id: 'a23',
    clubId: 'c1',
    hostId: 'u1',
    approvalMode: 'AUTO' as const,
    title: '台北信義區 ZUMBA 狂潮',
    date: '2023-11-19',
    time: '14:00',
    location: '台北市信義區市民廣場',
    price: 100,
    mode: RegistrationMode.OPEN,
    status: ActivityStatus.OPEN,
    currentAppCount: 200,
    level: Level.BEGINNER,
    image: 'https://picsum.photos/id/1060/600/400',
    description: '跟著節奏跳動，釋放壓力的音樂派對。',
    tags: ['Zumba', '舞蹈', '健身'],
    lat: 25.0375, lng: 121.5637,
  },
  {
    id: 'a24',
    clubId: 'c1',
    hostId: 'u1',
    approvalMode: 'AUTO' as const,
    title: '新竹科學園區羽球對抗賽',
    date: '2023-11-30',
    time: '19:00',
    location: '新竹市科學園區體育館',
    price: 400,
    mode: RegistrationMode.LIMITED,
    status: ActivityStatus.OPEN,
    maxParticipants: 40,
    currentAppCount: 38,
    level: Level.ADVANCED,
    image: 'https://picsum.photos/id/1061/600/400',
    description: '竹科人的運動時光，高水準對抗。',
    tags: ['羽球', '競技', '竹科'],
    lat: 24.7700, lng: 121.0000,
  },
  {
    id: 'a25',
    clubId: 'c2',
    hostId: 'u1',
    approvalMode: 'AUTO' as const,
    title: '嘉義阿里山健行日',
    date: '2023-12-05',
    time: '08:00',
    location: '嘉義縣阿里山國家森林遊樂區',
    price: 200,
    mode: RegistrationMode.OPEN,
    status: ActivityStatus.OPEN,
    currentAppCount: 50,
    level: Level.BEGINNER,
    image: 'https://picsum.photos/id/1062/600/400',
    description: '森林浴、神木林，享受芬多精的洗禮。',
    tags: ['健行', '嘉義', '風景'],
    lat: 23.5100, lng: 120.8100,
  },
  {
    id: 'a26',
    clubId: 'c1',
    hostId: 'u1',
    approvalMode: 'AUTO' as const,
    title: '桃園中壢籃球夜鬥',
    date: '2023-11-16',
    time: '20:30',
    location: '桃園市中壢區中正公園',
    price: 0,
    mode: RegistrationMode.OPEN,
    status: ActivityStatus.OPEN,
    currentAppCount: 18,
    level: Level.INTERMEDIATE,
    image: 'https://picsum.photos/id/1063/600/400',
    description: '中壢區熱門場地，歡迎報隊。',
    tags: ['籃球', '街頭', '熱血'],
    lat: 24.9580, lng: 121.2280,
  }
];

export const MOCK_POSTS: Post[] = [
  {
    id: 'p1',
    clubId: 'c1',
    author: { id: 'u1', name: 'Alex Chen', avatar: 'https://picsum.photos/id/64/200/200', isAdmin: true },
    type: PostType.ANNOUNCEMENT,
    content: '各位球友注意，下週二的場地因體育館整修暫停一次，請大家不要白跑一趟喔！我們將在週四加開一場補償大家。',
    createdAt: '2023-11-10T10:00:00Z',
    likes: 24,
    comments: 5
  },
  {
    id: 'p2',
    clubId: 'c1',
    author: { id: 'u2', name: 'Sarah Wu', avatar: 'https://picsum.photos/id/65/200/200', isAdmin: false },
    type: PostType.SHARE,
    content: '昨天晚上的比賽太精彩了！謝謝教練的指導，覺得反手拍有進步，下次再來挑戰 💪',
    images: ['https://picsum.photos/id/101/400/300', 'https://picsum.photos/id/102/400/300'],
    createdAt: '2023-11-09T22:30:00Z',
    likes: 45,
    comments: 12
  },
  {
    id: 'p3',
    clubId: 'c1',
    author: { id: 'u1', name: 'Alex Chen', avatar: 'https://picsum.photos/id/64/200/200', isAdmin: true },
    type: PostType.PHOTO,
    content: '週末團練大合照！大家笑容都很燦爛 😁 歡迎新朋友加入我們這個大家庭！',
    images: ['https://picsum.photos/id/103/800/600'],
    createdAt: '2023-11-05T09:00:00Z',
    likes: 67,
    comments: 8
  },
   {
    id: 'p4',
    clubId: 'c2',
    author: { id: 'u3', name: 'David Lee', avatar: 'https://picsum.photos/id/68/200/200', isAdmin: true },
    type: PostType.ANNOUNCEMENT,
    content: '【重要】合歡北峰活動行前說明會將於明晚 20:00 線上舉行，請有報名的夥伴務必參加，我們會講解裝備檢查與天氣預報。連結將發送至 Line 群組。',
    createdAt: '2023-11-15T12:00:00Z',
    likes: 30,
    comments: 15
  }
];

export interface SportCategory {
  name: string;
  items: string[];
}

export const SPORTS_HIERARCHY: SportCategory[] = [
  { name: '所有運動', items: [] },
  { name: '球類運動', items: ['羽球', '籃球', '排球', '網球', '桌球', '棒球', '足球', '高爾夫', '匹克球', '橄欖球', '保齡球'] },
  { name: '戶外探索', items: ['登山', '路跑', '單車', '露營', '攀岩', '滑板', '健行', '溯溪', '滑雪'] },
  { name: '水上活動', items: ['游泳', '衝浪', '潛水', 'SUP', '泛舟', '自由潛水', '滑水', '獨木舟'] },
  { name: '格鬥競技', items: ['拳擊', '柔道', '泰拳', '巴西柔術', '空手道', '跆拳道', '劍道', '角力'] },
  { name: '身心靈', items: ['瑜珈', '皮拉提斯', '冥想', '空中瑜珈', '太極'] },
  { name: '健身塑形', items: ['重訓', '有氧', 'CrossFit', 'TRX', '街頭健身', 'Zumba', '壺鈴'] },
  { name: '舞蹈律動', items: ['街舞', 'K-POP', '國標舞', '芭蕾', '爵士舞', 'Swing'] },
  { name: '極限運動', items: ['跑酷', 'BMX', '滑板', '直排輪'] },
  { name: '休閒娛樂', items: ['飛鏢', '撞球', '射箭'] },
];

export const TAIWAN_CITIES = [
  '全台灣',
  '台北市', '新北市', '基隆市', '桃園市', '新竹市', '新竹縣', '苗栗縣',
  '台中市', '彰化縣', '南投縣', '雲林縣', '嘉義市', '嘉義縣',
  '台南市', '高雄市', '屏東縣',
  '宜蘭縣', '花蓮縣', '台東縣',
  '澎湖縣', '金門縣', '連江縣'
];
